version: '3.7'

networks:
  default_network:
    driver: bridge

services:

    ###########
    ## panel ##
    ###########
    panel:
      container_name: panel
      hostname: panel
      volumes:
        - ./services/panel:/panel
      build:
        context: ./services/panel
        args:
          - HTTP_PROXY
          - HTTPS_PROXY
          - NO_PROXY
      depends_on:
        - mongodb
      environment:
        LOG_LEVEL: 'INFO'
        HOST: '0.0.0.0'
        PORT: '80'
        GUNICORN_MAX_REQUESTS: '10000'
        GUNICORN_WORKERS: '1'
        PYTHONUNBUFFERED: '1'
      networks:
        default_network:
          aliases:
            - panel
      expose:
        - 80
      ports:
        - 8000:80
#      command: honcho start
      command: python

    #############
    ## MongoDB ##
    #############
    mongodb:
      container_name: mongodb
      hostname: mongodb
      image: mongo:xenial
      volumes:
        - ./data/mongodb:/data/db
      networks:
        default_network:
          aliases:
            - mongodb
      expose:
        - 27017
      ports:
        - 27017:27017

    ###################################
    ## NoSQLClient (Management Tool) ##
    ## MongoDB visualizer            ##
    ###################################
    nosqlclient:
      container_name: nosqlclient
      hostname: nosqlclient
      image: mongoclient/mongoclient
      depends_on:
        - mongodb
      environment:
        MONGO_URL: 'mongodb://mongodb:27017/'
      volumes:
        - ./data/nosqlclient:/data/db
      networks:
        default_network:
          aliases:
            - nosqlclient
      expose:
        - 3000
      ports:
        - 9000:3000
